//
// orderTalent.cs
//
// Created on 8/31/2016
//
// Author:
//       Auston Lopez <MRPOWERZ83@me.com>
//
// Copyright (c) 2016 
//
//
using System;
namespace warhammerRPGCB
{
	public class orderTalent
	{
		string cardName;
		string cardText;
		int stanceRed;
		int stanceGreen;
		public orderTalent()
		{
			orderTalent aqshy = new orderTalent();
			aqshy.cardName = "Aqshy, Lore of Fire: Bright Order";
			aqshy.cardText = "When you perform a Bright )rder spell action that deals damage," +
				"for each 2 additinal power you spend you may increase the damage caused boy that Spell action by 1";
			aqshy.stanceRed = 3;
			aqshy.stanceGreen = 1;

			orderTalent shyish = new orderTalent();
			shyish.cardName = "Shyish, Lore of Death: Amethyst Order";
			shyish.cardText = "If a living creature dies on your turn after casting one of your Amethyst" +
				"Order spells, you may immediatley spend 1 power to add or remove a recharge token" +
				"from any one of you Amethyst Order spells";
			shyish.stanceRed = 2;
			shyish.stanceGreen = 2;

			orderTalent chamon = new orderTalent();
			chamon.cardName = "Charmon, Lore of Metal: Gold Order";
			chamon.cardText = "When casting a Gold Order spell you may spent 1 power to convert one" +
				"of you characteristic dice to a concervative die regarless of your current stance";
			chamon.stanceRed = 1;
			chamon.stanceGreen = 3;

			orderTalent ghur = new orderTalent();
			ghur.cardName = "Ghur, the Lore of the Beasts: Amber Order";
			ghur.cardText = "While you are in Beastform, you may spend 1 power to perform an " +
				"extra manoeuver on your turn. You may only gain one extra manoeuver per turn.";
			ghur.stanceRed = 3;
			ghur.stanceGreen = 1;

			orderTalent ghyran = new orderTalent();
			ghyran.cardName = "Ghyran, the Lore of Life: Jade Order";
			ghyran.cardText = "When casting a Jade Order spell whoes season trait matches the current season," +
				"add on fortune die to your die pool. When castinf a Jade Order spell whoes season trait is" +
				"the opposite of the current season, add one issfortune die to you dice pool.";
			ghyran.stanceRed = 2;
			ghyran.stanceGreen = 2;

			orderTalent hysh = new orderTalent();
			hysh.cardName = "Hysh, the Lore of Light: Light Order";
			hysh.cardText = "After you cast a Light Order spell, you may spent 1 power" +
				"to add or remove a recharge token to that spell, or to a condition card generated by the spell.";
			hysh.stanceRed = 1;
			hysh.stanceGreen = 3;

			orderTalent darkMagic = new orderTalent();
			darkMagic.cardName = "Dark Magic";
			darkMagic.cardText = "You can learn and cast Dark Magic and Chaos spells. When channelling power" +
				"or casting a spell, add one experties die to you dice pool. If one or more exertion or delay are generated, add" +
				"1 chaos star to the results. \r\n" +
				"Channelling and Spellcraft checks gain:\r\n" +
				"2 Bane: Add 1 chaos star to the results pool";

			orderTalent ulgu = new orderTalent();
			ulgu.cardName = "Ulgu, Lore of Shadows; Gray Order";
			ulgu.cardText = "When you performe a Gray Order Spell action, you may spend 1 additinal" +
				"power to add or remove 1 recharge token to or from that action";
			ulgu.stanceRed = 2;
			ulgu.stanceGreen = 2;

			orderTalent azyr = new orderTalent();
			azyr.cardName = "Azyr, Lore of the Heavens: Celestial Order";
			azyr.cardText = "When you perform a Celestial Order Spell action, you may spent 1 additinal" +
				"power to add 1 fortune die to your check to cast that spell";
			azyr.stanceRed = 1;
			azyr.stanceGreen = 3;


		}
	}
}

